//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SessionProgrameSubjectSettingTable
    {
        public int SessionProgrameSubjectSettingID { get; set; }
        public int UserID { get; set; }
        public int SessionID { get; set; }
        public int ProgrameID { get; set; }
        public int AnnualID { get; set; }
        public int SubjectID { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime RegDate { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual AnnualTable AnnualTable { get; set; }
        public virtual ProgrameTable ProgrameTable { get; set; }
        public virtual SessionTable SessionTable { get; set; }
        public virtual SubjectTable SubjectTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
