//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class StudentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTable()
        {
            this.AttendanceTables = new HashSet<AttendanceTable>();
            this.ExamMarksTables = new HashSet<ExamMarksTable>();
            this.SchoolLeavingTables = new HashSet<SchoolLeavingTable>();
            this.StudentPromoteTables = new HashSet<StudentPromoteTable>();
            this.SubmissionFeeTables = new HashSet<SubmissionFeeTable>();
        }
    
        public int StudentID { get; set; }
        [Required(ErrorMessage ="Please Select Session")]
        public int SessionID { get; set; }
        [Required(ErrorMessage = "Please Select Program")]

        public int ProgrameID { get; set; }
        public int UserID { get; set; }
        [Required(ErrorMessage = "Please Enter Student Name")]

        public string Name { get; set; }
        [Required(ErrorMessage = "Please Enter Father name")]

        public string FatherName { get; set; }
        [DataType(DataType.Date)]

        public System.DateTime DateofBirth { get; set; }
        [Required(ErrorMessage = "Please Enter Gender")]

        public string Gender { get; set; }
        [Required(ErrorMessage = "Please Enter Contact Number")]

        public string ContactNo { get; set; }
        [Required(ErrorMessage = "Please Enter  CNIC")]


        public string CNIC { get; set; }
        [Required(ErrorMessage = "Please Father Enter  CNIC")]

        public string FNIC { get; set; }
        public string Photo { get; set; }
        [Required(ErrorMessage = "Please select Photo")]

        [NotMapped]
        public HttpPostedFileBase PhotoFile { get; set; }
        [Required(ErrorMessage = "Please select Admission Date")]


        [DataType(DataType.Date)]

        public System.DateTime AddimissionDate { get; set; }
        [Required(ErrorMessage = "Please Enter Pervious School Name")]

        public string PreviousSchool { get; set; }
        [Required(ErrorMessage = "Please Enter Previous Percentage")]

        public Nullable<double> PreviousPercentage { get; set; }
        [Required(ErrorMessage = "Please Enter Email Address")]

        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "Please Enter Address")]

        public string Address { get; set; }
        public string FathersGuardinasOccupationofProffision { get; set; }
        [Required(ErrorMessage = "Please Enter Nationality")]

        public string Nationality { get; set; }
        [Required(ErrorMessage = "Please Enter Religion")]

        public string Religion { get; set; }
        [Required(ErrorMessage = "Please Enter Caste")]

        public string TribeorCaste { get; set; }
        [Required(ErrorMessage = "Please Enter postalAddress")]

        public string FathersGuardinasPostalAdress { get; set; }
        [Required(ErrorMessage = "Please Enter Phone ")]

        public string PhoneOffice { get; set; }
        [Required(ErrorMessage = "Please Enter phone Resident")]

        public string PhoneResident { get; set; }
        [Required(ErrorMessage = "Please Select Class")]

        public int ClassID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceTable> AttendanceTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamMarksTable> ExamMarksTables { get; set; }
        public virtual ProgrameTable ProgrameTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolLeavingTable> SchoolLeavingTables { get; set; }
        public virtual SessionTable SessionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPromoteTable> StudentPromoteTables { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmissionFeeTable> SubmissionFeeTables { get; set; }
        public virtual ClassTable ClassTable { get; set; }
    }
}
